#!/bin/bash

set -eu

# Edit these to configure the paths where you installed the libraries.
FOUNDATION_DIR=../foundation
PRETTIFY_DIR=../code-prettify

# These are inside the wellylang.org repo.
SOURCE_DIR=src
BUILD_DIR=build

# Remove relics of previous builds.
mkdir -p $BUILD_DIR
rm -rf -- $BUILD_DIR/*
cat >$BUILD_DIR/README.txt <<EOF
These files are auto-generated by "make.sh". Do not edit them.
EOF

# Copy needed libraries into place.
mkdir -p $BUILD_DIR/js
mkdir -p $BUILD_DIR/css
cp -R $FOUNDATION_DIR/js/* $BUILD_DIR/js
cp -R $FOUNDATION_DIR/css/* $BUILD_DIR/css
cp -R $PRETTIFY_DIR/src/prettify.js $BUILD_DIR/js
cp -R $PRETTIFY_DIR/src/prettify.css $BUILD_DIR/css
cp -R $PRETTIFY_DIR/styles/sunburst.css $BUILD_DIR/css
cp -R src/js/* $BUILD_DIR/js
cp -R src/css/* $BUILD_DIR/css

run_nancy () {
  local source=$1
  local target=$(echo $source | sed 's,/,_,g').html
  nancy --root $SOURCE_DIR template.html $source > $BUILD_DIR/$target
}

run_nancy index
run_nancy project_goals
run_nancy installation
run_nancy first_program
run_nancy question_answer
run_nancy data_types
run_nancy variables
run_nancy operators
run_nancy language_comparison
run_nancy about
run_nancy contact

run_nancy history
run_nancy history/declaration
run_nancy history/dynamic
run_nancy history/field_constnesses
run_nancy history/for_array0

run_nancy basic_syntax
run_nancy basic_syntax/newlines
